# Generated by Django 4.0.2 on 2022-02-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_post_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.TextField(default='Notice Header', max_length=255),
        ),
    ]
